#!/bin/bash
case "$(file -Lb --mime-type -- "$1")" in
  image/*)
    chafa -f sixel -s "$2x$3" --animate off --polite on -t 0.9 --bg "#ffffff" "$1"
    ;;
  text/*)
    cat "$1"
    ;;
  *)
    case "$1" in 
      *.py | *.js | *.json | *.conf | *.kdl | *.ts | *.sh | *.yaml | *.yml | *.nix)
      cat "$1"
      ;;
    esac
    ;;
esac
